### PR TITLE
send-mail-with-reason

### PR DESCRIPTION
**Pull request by priyesh-infobeans**
Please merge the send-mail-with-reason branch with development branch.

Development Done
A copy of email is send to practice head  with reason whenever a team member is rated with +1 or -1

### CODE REVIEW

**Comment by abhijeet-infobeans** [comment]
Following listed changes are required, before move on this further.
1. Change in subject line
$subject = 'Parakh - '.$team_member_name.' has been rated';
Subject will be...... Parakh - New rating alert
2. Remove hard coded email i.e. $to['email'] = 'priyesh.mehta@infobeans.com';
3. Write proper comment before function call.
4. This code fail to handle rating without comment scenario.
5. Rating reason must be in separate line.

**Comment by priyesh-infobeans** [comment]
Changes made as per the review comments.

**Comment by abhijeet-infobeans** [comment]
Use 
if(trim($work_desc) != ''){
instead of 
if($work_desc != ''){

**Comment by priyesh-infobeans** [comment]
Changes made as per the comments.

**Comment by abhijeet-infobeans** [comment]
:grapes:

**Pull request merged**
